apiVersion: v2
name: metal-lb
description: A Helm chart for MetalLB
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: metallb
    version: 0.14.9
    repository: https://metallb.github.io/metallb