apiVersion: v2
name: metal-lb
description: A Helm chart for Kubernetes
type: application

version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: metallb
    version: 0.15.2
    repository: https://metallb.github.io/metallb
    condition: metallb.enabled
    tags:
      - metallb