# UFW configuration variables

# Ports that should be open for external access (Laptop → Server)
ufw_external_ports:
  - { port: 22, proto: "tcp", comment: "SSH access" }
  - { port: 6443, proto: "tcp", comment: "Kubernetes API Server" }
  # - { port: 31800, proto: "tcp", comment: "KubeVirt Web Console (if enabled)" }

# Kubernetes NodePort range (only open if needed)
ufw_nodeport_range:
  - { port: "30000:32767", proto: "tcp", comment: "Kubernetes NodePort range" }

# Internal Kubernetes Network Subnets
ufw_internal_subnets:
  - { subnet: "10.42.0.0/16", comment: "Allow Pods subnet" }
  - { subnet: "10.43.0.0/16", comment: "Allow Services subnet" }

# Internal Cluster Traffic (Only inside the cluster)
ufw_internal_ports:
  - { port: "2379:2380", proto: "tcp", comment: "etcd HA Cluster" }
  - { port: 8472, proto: "udp", comment: "Flannel VXLAN" }
  - { port: 10250, proto: "tcp", comment: "Kubelet metrics" }
  - { port: 51820, proto: "udp", comment: "WireGuard IPv4" }
  - { port: 51821, proto: "udp", comment: "WireGuard IPv6" }
  - { port: 5001, proto: "tcp", comment: "Spegel Registry" }
