apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  releaseName: external-secrets
  targetNamespace: external-secrets
  storageNamespace: external-secrets
  dependsOn:
    - name: openbao
  chart:
    spec:
      chart: ./control-plane/manifests/external-secrets
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
    remediation: { retries: 3 }
  upgrade:
    remediation: { retries: 3 }
