---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgDe/XQuiWVqsDy1ely821XpKnX1StJKZnhOHn0O6oQE+WCaKeoieGS++wEfBgfD9b84/dXG79s8u2b+asvcylBk+QGk3CIVprFZMFT/9n7Ffbb0eqKWcjVMO16jwqxIUt1jdSUkZLlxOhPrdsF2L7HACSFWxAIt/V8KLt+KB4dZRW4K1WhjWEvu7klOCpPCeVs+kLTHA9v1IhCHYcuXYH2Naxu4b/Itj+f7Frr+q4WJf2pOJCXj+cCKBZ/ygeaKZq18rGKcmI5X951BmtjMEPT+u5MeNlHnLA+qPIP2KqRRHHVcRZCa5g8qTtGjG6asY2x5+Vpd5eKV7Ir7mquuK+Q7M+qT+DLCX1rHIJLFMb6ciFlpx8seMPdIhYkuWDTcqT/yLKJL5j1oyOmntgBTKRlop3CzwPC3ks7vnfaqwv9/ia3Ujyoi9Fe9GMuikGhNp3MuIf1kAZArv531yabbF9vc8FESxA/fWJJZCXCdxly+I7jQedhUcy3airdeQBKoqvkAUF5nj61uEhZsft/pO9ClziWMFHkUZx0j1zWRoaJcjcUvUnfDcPYzn/1YG5XikeOOqW06+nRu0cl/HXFW+5x8m+p7qwzjtC/AJLRFa1jSFSlAC52gzd2OXSrU72+PBXX81hJInXH846oZ6w8M9s3W3wQ4KIimuXHhp7H6cqLtr82ElsxkrT9b3QnQ9cZgYMwSyfvnbZ07MTT17vl4Otie
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-db-credentials
      namespace: keycloak
