---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgAVkhfVZUP+gHQ+1CSKEdyHLnZPyY3acBONnFrOtvLu4o1bqxkSgN0RxUpOSv1lktUmJJ3Gf8WSzPID28moQ9vJCpSrCoDVj1rx5WNGcrNC3I9KipadLZPGG3+r/jyLaVTUFZSxz8D7806htygoEHjM54jhAqIw697gIiY2ZjjKW64KBv2rESaTCmMQFK2CIeKCjBX1gBkoWtJPR/VwPaTFgPej+klXp2ZgeNSdxlg5wVIrgb9KLV3iqstIg3yjZh4QGKel+Eqf3eOeMPPi3mxYPDpXAelc0EnXlB6KTyDl9560b1JEDyo1/3yKmLLmlOz2aVp7Ln4qVVsnufGMNLEUkDu6RJAST0jL4Yfkqj+c4SUJhzC8OsiFQSf121PHveSYMPppjLSUf/tKHkylqaSWV2k8x8gZWmppwRUjyVaIS5QN+3D6N5uZO3+btLtxD1285XSn46KU9afWx5a9+36B/rjP61HcvxIWVIqosKZH2KBfTrA3dGFfRkI4IlZ6JDDT/vK+ixLOLJhR/excLqA2j+T3HdEFPnCgQ7XLhhNCnEbQXyLNNy3eLCRQYJu06k+jzhBrCZLu8dnoxMnLsjZJOme2l8d2T3Pv+jpyezQWq06iGYcM7zmdRvfyjYljiu/ydVw35e5p7rZFKSUM3BPZDDFnVntPIwF6aU8nP1tAiYG+3CnDAenFbkQreW9WvA1EMxWjoHR0iA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-db-credentials
      namespace: keycloak
