---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-creds
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgApahv0/Fsgy3Fb0Uwq2mylccf10sSQJ1xbJbGSsKdA9IN1ITtHRS5/EdGVwJUfsEBYzO9BxV9se0Tb8dChLSFkFWKAuG3jmigTNMaScjcKsUFQjUOEdfiuJks29lY93Kn4wpBDO6ZgKaGQrIuCncmrCm57bgOb1LYrdd29F06I2D/FGnrOz9ZSNnuXKGvrINjTGjVcNrNbwqKjYedX1af47QZ4eKEYflNwD8Io3VIoDNNVvEP13ZcdDj1FwnokbKO+8rQ9csxkmzMzu/068a8P3vRZVYABJn3QSTJE+bO+F8Iiko3rmY1fgEq+uSvdJcqIS6COdU/FwjqAvA6cD3qHVSr+CnGp3maALGbOt+hCYfiPHEkFc4MPAePMh/a+5v1BuiB3aF75dFlsKqCwa4dzQfXGWqovXHx7e3IeIH0WIMSv0Wm1JCvXVU8nn7hdYtZ7Osg6He1y0f1cU9w/X5hxxEVgOBO4xD0DjXeSbzVoaEnGxQe7Hui7y8kjJUhHcB5MWmzE7OCnzHd+JTWcHV1O9AAjhOPO2/0uDXx3pj0BcJ4AGUfssNV684lXkVqy41jknvIA8fFn0hmn4ei2PvhJuDeVdMGSjivCZIcESYDvNdIPQmwxBtQ4MoKZOn72z69DICGDECkVFjck+ZmP9TSm3q4A6is1xBytjFJ7VYISiEazeBapgabXWZbFbtEhmM1/QESnfQ09a5qARPo=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-creds
      namespace: keycloak
