---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBPaideMboCn9A88zKJWKyBO/1DRDAiPrbsBO9dtW/RNa+57bCUtuZLGlivAp2qM3t3XbseILLStNWwZTwQIG3n7h2bi2JIjtg5OY0YckMCI/woFYh9lkt0+vCB/M0z2t51xNUQWN4NiSZW1Q5l7O5cTYVxcYj770FNSKa4OENQlNXevtGJodgtT20fpRsREAbroKIpFi2jKv2fnbCVK57Byc7SdzYxjyd+972qEP7Fz5wAX7i8tyGWBSVvpufgewoEWPp9Hf3bYBcb4bVzul8OKdsBEPnJ01rymyU5AQU0YEAenVR2S85O1RFc9420CKZE6ez/bu0amPigZj5Xz0ZGwFLG3L1RX2GIS8f1jmx7D3WMKc+J3GBiKhbAL8wxSZi4rr00ITz8AQhxS7kQefDZQa/qOSuYBBQVmkpVodtcdM4enQ+MkhK0FymPdOislYvExNucSAoHymjTxP63z7M96blXqATBDj/CBB9y2AMHwy2MT94X8ZeOvB/t2wIdKbA7l1458u4h+5DNcUMWglv/j3xLtAZGViS512mu0Bdju/itDz2EpTOhbtqfvdLbBmOJryPeoVVbYQ+q23A5KFqkcFgEE2b0N51M4n3lv8Aq42Lv8V+eOoJ0f+FyoEL++9U5/C9LlnV8/INjwvEkIoRBm2PZwVU2MRU912rbu66NuwoLwrDHsfkT2+nxr3V3VOc1hpmBPvI636smVH5Rp1WL0GfV4NX3kBDzqBZloldwO3om+k1ECzQwELG0zPTy3JJT6rsAcc/oSCSM7mPCqK0QNAf7hP1SzygFyL9fcdk0aosC1QAm9v+40sxLEpQ76Qdlsss6iC2Rw9TL1WYuS5g5g9AHq5KrgaY3J7LhsJW3ezNHrw2skq7jHInw72pyFV6/kEybkoO+L0tB2xjhTnQqOppkzlwc0XsqLzb3XluN
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared
