apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 30m
  releaseName: cert-manager
  targetNamespace: cert-manager
  storageNamespace: cert-manager
  chart:
    spec:
      chart: ./control-plane/manifests/cert-manager
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation: { retries: 3 }
  upgrade:
    crds: CreateReplace
    remediation: { retries: 3 }
