apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cloudflare-cluster-store
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    kubernetes:
      remoteNamespace: external-dns
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: kube-system
      auth:
        serviceAccount:
          name: external-secrets-sa