apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cloudflare-local
    kind: SecretStore
  target:
    name: cloudflare-api-key
    creationPolicy: Owner
  data:
  - secretKey: apiKey
    remoteRef:
      key: cloudflare-api-key
      property: apiKey
