apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cloudflare-local
    kind: SecretStore
  target:
    name: cloudflare-api-key
    creationPolicy: Owner
  data:
  - secretKey: apiKey
    remoteRef:
      key: apiKey
