apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: external-dns
rules:
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-cert-manager-sa
  namespace: external-dns
subjects:
- kind: ServiceAccount
  name: external-secrets-sa
  namespace: cert-manager
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
