apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cloudflare-local
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    kubernetes:
      remoteNamespace: external-dns