websiteName: &websiteName web.tineochristopher.com

image: nginx:alpine

service:
  internalPort: 80
  externalPort: 80
  type: ClusterIP

ingress:
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - secretName: staging-tineochristopher-com