websiteName: &websiteName web.tineochristopher.com

image: nginx:alpine

service:
  internalPort: 80
  externalPort: 80
  type: ClusterIP

ingress:
  className: traefik
  annotations:
    # kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
  tls:
    - hosts:
        - *websiteName
      secretName: selfsigned-tineochristopher-com
