websiteName: &websiteName web.tineochristopher.com

image: nginx:alpine

service:
  internalPort: 80
  externalPort: 80
  type: ClusterIP

ingress:
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    external-dns.alpha.kubernetes.io/hostname: *websiteName
  tls:
    - hosts:
        - *websiteName
      secretName: staging-tineochristopher-com