apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: "https://github.com/TineoC/homelab.git"
    targetRevision: main
    path: ./control-plane/apps/argocd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
