apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-pool
  namespace: {{ .Release.Namespace }}
spec:
  addresses: {{ toYaml .Values.addressPool.addresses | nindent 4 }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-l2-advertisement
  namespace: {{ .Release.Namespace }}
