---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgC9Lo4XtORY/SFK/YRCZDrnEbUm63fcP+X/SR2eb1w3PErEpFhANjaYIZ8twnKGItyhBmlDZeHqWPjxNfgUyt0uOsJKyRw2KWJSOLJvDB/4M4j+hMvZcWp2MXdFzzlhv63ZNfUcImBpw0JXA4smf7UJ+69Bw6nCXc0iCZ62ps4HZOn13jWtM/IMml/CU1dVgeRGKtK8DpgyPbt/KFfVum0E0LDugUXDe3vpA9cRrJlCfKK6r33iXvQmWA/qqu6hhXy+XjhF2Uu513as1U7fT06E3fz4zg2GC1KXQbIQomI5NvywUiMsbO43FeXqgiYeHfbWHAj/k8QcKPZPwkIWlWwblyWUCVdO0iqOieblkpatoTErZoKWgZzl0aIkwI4n2sjlQKwCQeabtzRPQ66aKTeVBNDw+9VeBuPRJfU4cRLIn63OGpyx9ziUXUXo/kdycBXhqSvGyW/5ZHfsjsSdLRmqsYugLYjTcaysj2P5rekEUR+LvhNJbJF5+q7lCLMbqFp8p9Lezzg1d5SBC5a/o43EE2bQjAJo8vWeilBEh/ittKTcXM4IyFo0iTZAMvM1+kT37Xy3r2YJ55JR0XqAbdOKeUMMn/NbA1uuq7Vrr9KhB9howC2JmpMah4Uxj0l1psczYmWwf1/w+1tEr0PyGR7QvMo/nL0cK5zLcJXF6FZJaPBpSLDE7OPLSzzfpFiyGC+EkPSYiaHWXmHHlzPcPuWjAzcEy6uvLzwhlur6mQPN4FmEThx8sue3Wl/TV40gKcVf8JNIlkJLtQCQoU9rGmQiq7AHCB0WT2EXzUwWGYks+0wLZ82pplkhZuskyr9AfZOyPOnh4rd6hk9ZN5jHh0swXTRyyQTZGuZJXljk1oVoEt0fLrIzt1xmZ7TJ7fZmbBBjVGGPPYunB86tdRMwltj3dOe6T2UkW3P177fEarxt
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-cloudflare-tunnel
      namespace: cloudflared
