---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgArXPCePYgbToDp9qEptvCJkyvsX+T1rgCape8iEqE6OKA84SKxWR/4eO7Lv0ZSR486KoOPpHqYmBTfCObrFYzO23iVJqj68tLr7ngQeitn3PPh95F26p148nhsW5oKYa4EQ/Ff+v+h/WxmuzmOXNaTFE/F44XcWSB2N+u4WlL2Ii5a44NJWGQQE2F7QSub90TErWmFCLL5hYhwJfhrCpNBYV1l4FKktZOCzRHJ1mNuHok2LswR0QP4npE7C37wx6m+ImeNRDg8SUJEy1ZZDCryA8s2GXtj88GBs7pEnKLmdHV7I3PsiNn2fn2o2gyWO0xV1tTvVf6ITCvOcY7EJ1MMkbJ65wTbTC8cgQer0HpmnlmV5HrXNiM+kTsFizV6qVJVmpwnUZoXF7qEPV4Tb2yEobzsLjgmpkRXESNDuGdqT3FnlJ74vcpRM2XnvDeWCkHFROVZD66+pFvMfViJvT3Ms+Q3N8ToHWeedc/3Ie+nZZ0Aj2wqmoglZ5HT4KjBt1f3thgWxOUUgFFX5pZDKQDnrwvnfSqP+aoXqol3pqW5oy+13o+j4+TGfq2itSelkijBAtV/JnW2ixgtZPO9sfOKDqKuuKchXR16mJmeAOuF7y6J3ohtPUP1qru+ChJn3IoJKCeCa6DwbT1ZNp7vBOOap/lRtBP2idDiSECPG8tVLIeCB9lNMNJqCTJ5P9HMNrChsSiPt2jayOCGlMmi1aRMYhJ0KXfPFoi9ITelD0bkiKf+dbysTgza66n8MOmjwR1DEgw6lHN84mIQ64ykb84+ufx8FMnlu4QbUwhV1IEp5yHszzl0i2qqpo7AZRbefkyw2y3+diZi9JZJUVHlRZMMslfyzQNc2lUr8fhodo/Wbji4prku8IcOAi4rY4I+WjKuiMVFXxk59sVAw+AarJZ3dyFlymDmwqMPHo9/qB7f
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
