apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTlRJMk16STBNRE13SGhjTk1qVXdOekUyTURJeU1EQXpXaGNOTXpVd056RTBNREl5TURBegpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTlRJMk16STBNRE13V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRM2h4dW8vNy9sb3lMSFVPY2c4VkNWMUQ2ZE1OZnlxTGd5eC9wT3hicjgKS3NsbVIzM05QTjNWd0VQQjQrT0RIdmxJb2pjUkF2M1FXRXVNbHB4NzQ5Mk5vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUVVd24veTFJYWUrWlExOWJQUGpvCjIrdWxkSjR3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnSGZ6S1kzY2kwN2lPc0VHOEdJdmZGSUlnOW1NRDJBQzMKc0d0ZDd5aGdqTmdDSUQ3eklKMEpWM0Zxc3RrVG9YKzFETHl1dXJkWmh5c1VzNnBMYkt3MFJUNm0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://192.168.1.10:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
- context:
    cluster: default
    user: oidc-user
  name: oidc
current-context: oidc
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJTjQ5TWlvRlE3eXN3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOelV5TmpNeU5EQXpNQjRYRFRJMU1EY3hOakF5TWpBd00xb1hEVEkyTURjeApOakF5TWpBd00xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJNb2FET3dwcWpVWmF4REwKUFQ2ZW5WUnJHMkJkeWY3MEJvZ0FSRDZmTk5vVUVISnlLSk5LSnI0aHdLYkNmRlZvc0lMWjVvaXMzbm9pTk5ZSwp0M0Zocm1DalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUTg1cEhWKzJISHBYQXlKYUVrY1dacjFuV0pTekFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQTRxUFRYcTBVWTZuL29WdktocE9SMlc0TGptK1BiUzNWSjZITXAvc3BKZUVDSVFEMExmQ1g4ZGdTdlJXdAoyZjNMK0VjczAycGJGZ00ySjNNSFNCNGluQnBZb2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZGpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM05USTJNekkwTURNd0hoY05NalV3TnpFMk1ESXlNREF6V2hjTk16VXdOekUwTURJeU1EQXoKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM05USTJNekkwTURNd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUXg4M0IreUFBZEZheG5YV0xhK3cxZHVreHAzS3ZKamdsRjZDMTVVK0RMCmR3YVd3UURxTUhhditEOTZRVFRLWlJqeXJ1aVlDOVI4Ym9DQWZaeTQvZFNObzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVQT2FSMWZ0aHg2VndNaVdoSkhGbQphOVoxaVVzd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ0JPelNTV05jeHpXQTIwVkRqNEpIekEyNzZlWjlZeGRPCkJJcmU2dDRWbkJnQ0lFbE5kcFVkVG9ueUdOK1MxQkFEVHZ3MnVTTjYyK3FScnJTUzFoWE1ER0xUCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUVQMjdaNjd6ODRsaGxoamsvWTNSM2xaMXc4eDlWZE9iNEVtTS93aURkQWRvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFeWhvTTdDbXFOUmxyRU1zOVBwNmRWR3NiWUYzSi92UUdpQUJFUHA4MDJoUVFjbklvazBvbQp2aUhBcHNKOFZXaXdndG5taUt6ZWVpSTAxZ3EzY1dHdVlBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
- name: oidc-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --oidc-issuer-url=https://keycloak.tineochristopher.com/realms/kubernetes
      - --oidc-client-id=kubernetes
      - --oidc-client-secret=IyQcpG7g2uFeb1SYrkR9OTtRT7AQ0MUp
      - --oidc-extra-scope=groups
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
