apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: {{ .Values.server }}
    email: {{ .Values.email}}
    privateKeySecretRef: {{ .Values.privateKeySecretRef }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingressClassName }}
