external-dns:
  logLevel: debug
  provider:
    name: cloudflare
  env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: apiToken
  policy: upsert-only
  domainFilters:
    - tineochristopher.com
  sources:
    - service
