external-dns:
  provider:
    name: cloudflare
  env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey
  policy: upsert-only
  domainFilters:
    - tineochristopher.com
  sources:
    - ingress
  extraArgs:
    - "--annotation-filter=external-dns.alpha.kubernetes.io/hostname!=_acme-challenge.*"