cloudflare:
  secretName: &cloudflareApiTokenSecretName cloudflare-api-token
  email: &cloudFlareEmail christophertineo02@gmail.com

external-dns:
  provider: cloudflare
  cloudflare:
    secretName: *cloudflareApiTokenSecretName
    email: *cloudFlareEmail
    proxied: true
  policy: sync
  registry: txt
  sources:
  - ingress