cloudflare:
  secretName: &cloudflareApiTokenSecretName cloudflare-api-token
  email: &cloudFlareEmail christophertineo02@gmail.com

external-dns:
  provider: cloudflare
  domainFilters:
  - "tineochristopher.com"
  cloudflare:
    secretName: *cloudflareApiTokenSecretName
    email: *cloudFlareEmail
    proxied: true
  policy: sync
  registry: txt
  txtOwnerId: homelab
  txtPrefix: ext-
  sources:
  - ingress