- name: Configure oidc in k3s server
  hosts: primary_servers
  become: true
  vars:
    keycloak_domain: https://keycloak.tineochristopher.com/realms/kubernetes
    oidc_client_id: "k3s-cluster"
    oidc_username_claim: "preferred_username"
    oidc_groups_claim: "groups"
  tasks:
    - name: Configure OIDC settings for K3s
      ansible.builtin.blockinfile:
        path: /etc/rancher/k3s/config.yaml
        block: |
          kube-apiserver-arg:
            - "oidc-issuer-url={{ keycloak_domain }}"
            - "oidc-client-id={{ oidc_client_id }}"
            - "oidc-username-claim={{ oidc_username_claim | default('preferred_username') }}"
            - "oidc-groups-claim={{ oidc_groups_claim | default('groups') }}"
      become: true

    - name: Restart K3s to apply OIDC config
      ansible.builtin.systemd:
        name: k3s
        state: restarted
        enabled: true
      become: true
