- name: Ensure K3s config directory exists
  file:
    path: "{{ playbook_dir }}/files"
    state: directory
    mode: "0755"

- name: Get kubeconfig file
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ kubeconfig }}"
    flat: yes

- name: Adjust kubeconfig host
  replace:
    path: "{{ kubeconfig }}"
    regexp: "127.0.0.1"
    replace: "{{ ansible_host }}"
  delegate_to: localhost
