- name: Install K3s
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -
  args:
    creates: /usr/local/bin/k3s
  register: k3s_install_output
  changed_when: k3s_install_output.stdout.find('Skipping k3s installation') == -1 and k3s_install_output.rc == 0

- name: Enable and start RKE2 service
  service:
    name: k3s
    enabled: yes
    state: restarted
