- name: Set default UFW policies
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: "incoming", policy: "deny" }
    - { direction: "outgoing", policy: "allow" }
    - { direction: "routed", policy: "deny" }

- name: Allow SSH access
  ufw:
    rule: allow
    port: 22
    proto: tcp
    comment: "SSH Access"

- name: Allow K3s inbound network rules
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  loop:
    - {
        port: "6443",
        proto: "tcp",
        comment: "K3s API Server & Spegel Registry",
      }
    - {
        port: "2379:2380",
        proto: "tcp",
        comment: "etcd HA (if using embedded etcd)",
      }
    - { port: "10250", proto: "tcp", comment: "Kubelet Metrics" }
    - { port: "8472", proto: "udp", comment: "Flannel VXLAN" }
    - { port: "51820", proto: "udp", comment: "Flannel Wireguard IPv4" }
    - { port: "51821", proto: "udp", comment: "Flannel Wireguard IPv6" }
    - {
        port: "5001",
        proto: "tcp",
        comment: "Embedded Distributed Registry (Spegel)",
      }

- name: Allow Internal Kubernetes Network Subnets
  ufw:
    rule: allow
    from: "{{ item.subnet }}"
    comment: "{{ item.comment }}"
  loop:
    - { subnet: "10.42.0.0/16", comment: "Pods subnet" }
    - { subnet: "10.43.0.0/16", comment: "Services subnet" }

- name: Reload UFW
  command: ufw reload
  changed_when: false

- name: Verify UFW Status
  command: ufw status verbose
  register: ufw_status
  changed_when: false

- debug:
    msg: "{{ ufw_status.stdout_lines }}"
