apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-gw-cert
  namespace: envoy-gateway-system
spec:
  secretName: public-gw-tls
  dnsNames:
  - "*.tineochristopher.com"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer