apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gw
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "*.tineochristopher.com"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: public-gw-tls