apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: __INGRESS_HOST__
    external-dns.alpha.kubernetes.io/target: "96.248.109.98"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - __INGRESS_HOST__
    secretName: __INGRESS_SECRET__
  rules:
  - host: __INGRESS_HOST__
    http:
      paths:
      - backend:
          service:
            name: web
            port:
              name: http
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
