---
- name: Ensure helm is installed
  package:
    name: helm
    state: present

- name: Ensure ArgoCD namespace exists
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present

- name: Add ArgoCD Helm repository
  kubernetes.core.helm_repository:
    kubeconfig: "{{ kubeconfig }}"
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Install ArgoCD via Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    update_repo_cache: true

- name: Apply ArgoCD application configuration
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'control-plane/apps/argocd/argocd.app.yaml') }}"
