- name: Ensure helm is installed
  package:
    name: helm
    state: present

- name: Ensure ArgoCD namespace exists
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present

- name: Add ArgoCD Helm repository
  kubernetes.core.helm_repository:
    kubeconfig: "{{ kubeconfig }}"
    name: argo
    repo_url: https://argoproj.github.io/argo-helm
