---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: internal-ca
spec:
  ca:
    secretName: internal-root-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-root
spec:
  isCA: true
  commonName: internal-root
  secretName: internal-root-ca
  issuerRef:
    name: {{ .Values.selfSignedIssuer.name }}
    kind: ClusterIssuer