---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.prodIssuer.name }}
spec:
  acme:
    server: {{ .Values.prodIssuer.server }}
    email: {{ .Values.global.email}}
    privateKeySecretRef: {{ toYaml .Values.prodIssuer.privateKeySecretRef | nindent 6 }}
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.global.email }}
          apiKeySecretRef: {{ toYaml .Values.cloudflare.apiKeySecretRef | nindent 12 }}