---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
spec:
  encryptedData:
    cloudflare_api_token: AgCv7ONPTRir7/Q++6DxVU7HYKnGyvXpK14eizoch6lK/4zPEAd/9DhzyvWcMMGkW5E48icIzd00BXn78e3qHHmiopMYIkfsXg5JB25r2risvRx3To6PVhlokgBOGBYneTDDiOHy6BTQGyIbQxev2yRywMPKGx5CEPVF8EfesApqR4yoPWYSQ1rRUwxRNYxCWJANTkd6UYA8J6vaT6CGvrocDyKzrRAOjCBTv3bjcK0gx62eYSe5QfbBAwkf+D2bkG0GdEL++8u1DUfZPQOuoLn0l5B+fmalYZqE25bNKmZw+u9QO9Vv9Pwbxf+HnPPFKaqPH/zQGiSC7CULvCrt+kAW3HjyVjkF5giWuc6Tfuum5DgCTVjXlAhJUmtE4TUQknl9gMa0fsLDBxRDty16hBTlGkNi5pp0KPuIOdWTuNKqyp5PWJtI/u1wCtB+RT9dlRGLVFvwFPgPyTS6a5cQvEN2g/gxPU+GNYhygmAEBlDibqX7VU5Bi4fBUvmcSqTdJTjO/Odz6mFXa9cGFnz59uYJxjnXljRGKtFBP+JSlki1SdsoY0RIKq26i4CPfaq6/D9WkGyPmp4Y/B6sCoIsH3ANgYVZLb7TcQOO4/CC0fCYMzlscAhTB5q0G+j6LeBPzDFBuUGTxR9BRGBmygFn96zAMWviH/rlCqCV3ABuyVmI70kXcU2dkvV4LbeZfsnZYcN0wb4C044BlepoLq/6RLAvVKeODtqPeTHLsM6AcKxILM7WjC08zP9N
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: default
    type: Opaque
