---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare_api_token: AgBZ412C3wsA+WbdviovFedItSo+ivKgMhXclmc7CYimWqpXkGMXlSCSRWp5gP+rqAIYWhpPUkArKxd+KMadjs4XRzDHHn0bEdC2HFuQXT6+vhJuFDR8helieeZXGLbMTLG1XjprhdgvpBWyl05c9gl9MGqHnrGjco2V/jXD4RpZUhGEtqnDwcLr2iUW44G6Fke3lozK13fp4080bBifhTNtUv656OwVStEcq/EZs9mukREC9sq6WJ7llqGTFQWUYfmZZ/SG9N3896TMDkUIVdjwjX6RoJrsll6sohR0hCiap/7nU3+UghICO908x9bzAzhnghfpLWuWKS4+pGo79EaaXmK62LtbIYKovxyvqNnixy57h9E8JH0QJzaHcKQY1VXBFnR9r4a4E4dBeROfpGy5mbjwZUw55HJ6kGHTS1cJTRAl5/YSlzsEk2hO8m49dYoERBAfHKwbXwaa8zdMbA92rFK2hRHH2ckn2s0V3diby5SKPLknbVsDxUsHyCL5e2N66nBys2Acj0sD2OAjVlAIbcFOnQvwWOnyLR9eoTHf0OdzcAt7Vv2ejIeJkmQNCHmG824HrFdGrstClxSvrsMAnR+JMgLlfOZADwwT2HFN21pBOpxiTWy9Hu/UB9gaAWYhDRXsLXJTHUC4qUIBtdB0t6FNeeFBWLNvY4mUgJL2b6kt3ildSqkbiHZPdBcDB4R9yfzHwyyoX2iRdvePyuAMSRsXv8vLxQEH/ps7Ky57rEW8ztiken99
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
