---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.stgIssuer.name }}
spec:
  acme:
    server: {{ .Values.stgIssuer.server }}
    email: {{ .Values.global.email}}
    privateKeySecretRef: {{ toYaml .Values.stgIssuer.privateKeySecretRef | nindent 6 }}