global:
  ingressClassName: &commonIngressClassName traefik
  email: &commonEmail christophertineo02@gmail.com

prodIssuer:
  name: &prodClusterIssuerName letsencrypt-prod
  privateKeySecretRef:
    name: *prodClusterIssuerName
  server: https://acme-v02.api.letsencrypt.org/directory

stgIssuer:
  name: &stgClusterIssuerName letsencrypt-staging
  privateKeySecretRef:
    name: *stgClusterIssuerName
  server: https://acme-staging-v02.api.letsencrypt.org/directory

selfSignedIssuer:
  name: selfsigned-cluster-issuer

cert-manager:
  installCRDs: true
  ingressShim:
    defaultIssuerName: *stgClusterIssuerName
    defaultIssuerKind: ClusterIssuer