global:
  email: &commonEmail christophertineo02@gmail.com

cloudflare:
  secret:
    name: cloudflare-api-key
    key: apiKey

prodIssuer:
  name: &prodClusterIssuerName letsencrypt-prod
  privateKeySecretRef:
    name: *prodClusterIssuerName
  server: https://acme-v02.api.letsencrypt.org/directory

stgIssuer:
  name: &stgClusterIssuerName letsencrypt-staging
  privateKeySecretRef:
    name: *stgClusterIssuerName
  server: https://acme-staging-v02.api.letsencrypt.org/directory

selfSignedIssuer:
  name: selfsigned-cluster-issuer

cert-manager:
  installCRDs: true
  config:
    kind: ControllerConfiguration
    enableGatewayAPI: true