apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-12"
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: control-plane
  source:
    repoURL: https://github.com/TineoC/homelab.git
    path: control-plane/manifests/external-secrets
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
