apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  sourceRepos: ["*"]
  sourceNamespaces: ["*"]
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
