apiVersion: v2
name: oauth2-proxy
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: oauth2-proxy
    version: 7.17.0
    repository: https://oauth2-proxy.github.io/manifests
  - name: redis
    version: 22.0.1
    repository: https://charts.bitnami.com/bitnami