oauth2-proxy:
  nameOverride: oauth2-proxy
  ingress:
    enabled: true
    className: nginx
    path: /oauth2
    pathType: Prefix
    hosts:
    - auth.tineochristopher.com
    tls:
    - hosts: 
      - auth.tineochristopher.com
      secretName: oauth2-proxy-tls
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-staging
      
      external-dns.alpha.kubernetes.io/hostname: auth.tineochristopher.com
      external-dns.alpha.kubernetes.io/target: 96.248.109.98
  config:
    existingSecret: oauth2-proxy-config
    configFile: |
      provider = "keycloak-oidc"
      oidc_issuer_url = "https://keycloak.tineochristopher.com/realms/kubernetes"
      whitelist_domains = [".tineochristopher.com", "web.tineochristopher.com"]
      email_domains = ["*"]
      redirect_url = "https://auth.tineochristopher.com/oauth2/callback"
      reverse_proxy = false
      upstreams = ["static://202"]
      allowed_groups = ["cluster-admins"]
      code_challenge_method = "S256"

      # Redis session store
      session_store_type = "redis"
      redis_connection_url = "redis://oauth2-proxy-redis-master.oauth2-proxy.svc.cluster.local:6379"
      redis_password = "password"

redis:
  architecture: standalone
  auth:
    enabled: true
    password: password
  master:
    persistence:
      enabled: true
      size: 1Gi