apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base

patches:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: dev.web.tineochristopher.com
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: nginx

labels:
- pairs:
    env: dev
