apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base

patches:
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: nginx
  patch: |
    - op: replace
      path: /spec/rules/0/host
      value: web.tineochristopher.com
    - op: add
      path: /metadata/annotations
      value:
        external-dns.alpha.kubernetes.io/hostname: web.tineochristopher.com
        external-dns.alpha.kubernetes.io/target: 96.248.109.98
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/server-snippet: |
          location /.well-known/acme-challenge/ {
            allow all;
            root /usr/share/nginx/html;
          }

labels:
- pairs:
    env: dev
