---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --credentials-file
        - /etc/cloudflared/creds/credentials.json
        - --protocol # https://github.com/cloudflare/cloudflared/issues/1176#issuecomment-2404546711
        - http2 # didnt seem to need the sysctl changes
        - --metrics
        - 0.0.0.0:2000
        - run
        - homelab-tunnel
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: tunnel-credentials
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: tunnel-credentials
