---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAp4CirxPiCyuiam18El4ptNlfP9WPrIx3onm5nrgIUppMPCSkVa1gF/RwCsEBHF9xobb4FZ5nLQ8oNRZdCeOhLIfCksVpNHdyhySk7GqSwR0wb05y1qdsvCds/3dPs4GdT9rXsISyHbyyRDvZISN7WhiQWIoCkkp1Ox0oWal2nDPITxF0PcvXLJoMY2Ayo1zmRDDbTq/vFNMDhXOIyZgh2xyd4UjmYJbdXzPvJfftxCXvGCipUH/NqsRcz+UE46JAspwY+fnU+q06KUpUIZunYfQqZHdOhAI73Nih3DvJq+o2USNgK30OxJRMcmxvWJZDc9M6ersMx7Vo0Ln3iZ0bU87lhz13K0rGg8Y4lqwXUdNhYxsIdrw72vJ+/Qjbidzq91o4Q29+YqtJJheFHQDc22T/s1zqSPvyg9ejDda2X/92L+8gMgSC2meBe9rwFGm/lSrWXvzmKAV0VfXeyO5MNzIl5G5KX9EpIs5Clao2WDA6mXWntXIv0pjSGySMk91k24WayEu2grQ9l9Zg++p5J4tpWdjlrtPYH66UIWrCYmUWmuyVrrb0Sxf+u0aK3h3+mFRUsG8SMVEkd0m8aBPYmuu9QYiUdC45bG66b88R8gSLMc45oOBW8uvbX2m/VYsOuis+7btR3ovTW1LVAAvWTinK0Jjk37hM0P1h+czkTMRci2HZz67zBxLgSEf6s7Bq7ofJGQkc3l+vrQHXtMekLUcNiKNy4OW5Lh1LDRJD9Oge2nS/EXHI63mhbv6+8QWk4Sx0OSWiHFa+PJD3yBkJM5reuAXEn9Yq7tX/oo34dOasGDMYPMAiMaYmUCtJ4VhG8neSGu415APB11JmkB3JDij60P/YCuwiOc04UoT7aljyYCHhUFBJUn7xlSUxZ/igvI475Cqpn90DOTQfjESKLfRKItgKK+Su3127uTkzN
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
