---
- name: Ensure required dependencies are installed
  apt:
    name:
      - curl
      - unzip
    state: present

- name: Ensure K3s directory exists
  file:
    path: /etc/rancher/k3s
    state: directory
    mode: "0755"
