- template:
    src: config-controlplane.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: "0644"

- name: Download and install K3s server
  shell: curl -sfL https://get.k3s.io | \
    INSTALL_K3S_VERSION={{ k3s_version }} \
    K3S_KUBECONFIG_MODE="644" \
    sh -
  args:
    creates: /usr/local/bin/k3s

- name: Enable and start K3s server
  systemd:
    name: k3s
    enabled: yes
    state: restarted

- name: Fetch K3s kubeconfig from control plane
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/tmp/kubeconfig_{{ inventory_hostname }}"
    flat: yes
  when: inventory_hostname in groups['primary_servers']

- name: Copy kubeconfig to files/config.yaml on localhost
  delegate_to: localhost
  become: false
  copy:
    src: "/tmp/kubeconfig_{{ hostvars[groups['primary_servers'][0]].inventory_hostname }}"
    dest: "{{ kubeconfig }}"
    mode: "0644"
  when: inventory_hostname == hostvars[groups['primary_servers'][0]].inventory_hostname

- name: Replace localhost IP with control plane IP in kubeconfig
  delegate_to: localhost
  replace:
    path: "{{ kubeconfig }}"
    regexp: "127.0.0.1"
    replace: "{{ hostvars[groups['primary_servers'][0]].ansible_host }}"
