- name: Copy k3s config
  copy:
    src: ./config/k3s.yml
    dest: /etc/rancher/k3s/config.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Install K3s
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -
  args:
    creates: /usr/local/bin/k3s
  register: k3s_install_output
  changed_when: k3s_install_output.stdout.find('Skipping k3s installation') == -1

- name: Enable and start RKE2 service
  service:
    name: k3s
    enabled: yes
    state: restarted

- name: Ensure K3s config directory exists
  file:
    path: "{{ playbook_dir }}/files"
    state: directory
    mode: "0755"

- name: Get kubeconfig file
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ playbook_dir }}/files/kubeconfig.yaml"
    flat: yes

- name: Adjust kubeconfig host
  replace:
    path: "{{ playbook_dir }}/files/kubeconfig.yaml"
    regexp: "127.0.0.1"
    replace: "{{ ansible_host }}"
  delegate_to: localhost
