apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: control-plane
  source:
    chart: gateway-helm
    repoURL: docker.io/envoyproxy
    targetRevision: v1.5.2
    helm:
      values: |
        controller:
          extraEnv:
            - name: SSL_CERT_FILE
              value: /etc/ssl/certs/custom-ca.pem
          extraVolumes:
            - name: oidc-ca
              secret:
                secretName: private-gw-tls
          extraVolumeMounts:
            - name: oidc-ca
              mountPath: /etc/ssl/certs/custom-ca.pem
              subPath: ca.crt
              readOnly: true

  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
