server:
  config:
    server:
      insecure: false
  type: LoadBalancer
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod" # Use cert-manager for TLS
    hosts:
      - argocd.tineochristopher.com
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.example.com
