apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
  - secretKey: apiToken
    remoteRef:
      key: cloudflare
      property: token
