---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    apiToken: AgDhfWnLHCGvLc1VsJe78DIBpNOvib5ri1T9oOw2BbYBFHivc5AOnqddYAO51fd8Vtm8sf3njfaww2NupGhUXJIK3kHTY8KjolHG/P2N8YyXVqdIvMiPoiKgM4CYa4GyUwXTE60/Pt92ve/QOSn9gkDnhlN4nPuiJjF8LFh0BXK9wO/2VRPBnvqHBAbgDA35zmM9h4XyPqKUHq8Ko1a/1Pl5c6RHyhXvum6wtQCk9DfCW9kwjA2X+fMn1g/TW6AsUTecRV6BCa0XUS3P7/Wih1X5uXyCkWl1BfdUWc7lnndAK+4eQao32hb++Nd8J6xo7dZba+lRy1Z6925zrcLVykyf/MpmlXXUQSatzrHic70LVPejATbICpOdBxuW4RhXdLxADd3/nBcyoDoVt7u99th7qPKhNYvvWET9wJEOXx7DdVEqDLaqIK2GF6S73YJaTEfWzLleimnrMC2V5WCBkl62gXWzGwPux0zAYpHa431DryUiKLQimpqfSJd6CE6GqbUa14OH8NdCE2yIgLg9cAn4h3oO9lRuG4TiPvYFTdnWqS2T1hhjv0TbErFUV9AJkvj1qAOx0lPVlQUSu3I20NrpJkUtIrb+yHA1Xhc4p99AnoDu9jVuOGMCHkg3J2acAaR+4/50a6FBx6byLS4OTCb3Oq1JskPML7vTXw5/vm8CTv4um+boozZqUBBmM3bKEP1jtjbdgrviNUOVX76xaqFqwhBXlzrsYtnbdZQYRZOUVQWKS/Z/FTrf
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
