- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Enable automatic security updates
  copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Allowed-Origins {
          "${distro_id}:${distro_codename}-security";
      };
      Unattended-Upgrade::Automatic-Reboot "true";

- name: Run unattended-upgrade manually
  command: unattended-upgrade -d
