---
- name: Ensure regular system updates
  hosts: rke2-cluster
  become: true
  roles:
    - apt-maintenance
    - ntp
    - ufw

- name: Install rke2
  hosts: primary-servers
  become: true
  roles:
    - rke2-controlplane

- name: Install rke2
  hosts: secondary-servers
  become: true
  roles:
    - rke2-agent

- name: Configure Kubeconfig
  hosts: localhost
  become: true
  tags:
    - k8s
  roles:
    - configure-kubeconfig
