- name: Ensure regular system updates
  hosts: cluster
  become: true
  roles:
    - apt-maintenance
    - ntp
    - ufw
- name: Install K3s in both controlplane and agents
  hosts: cluster
  become: true
  tags:
    - k8s
  roles:
    - k3s
