apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, certificates, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, gpgkeys, *, *, allow

    g, ArgoCDAdmins, role:admin
    g, developers, role:developer

    p, role:developer, applications, create, *, allow
    p, role:developer, applications, update, *, allow
    p, role:developer, applications, get, *, allow
    p, role:developer, applications, sync, *, allow

    p, role:readonly, applications, get, *, allow
