apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- ingress.yaml

patches:
- target:
    kind: ConfigMap
    name: argocd-cm
  path: argocd-cm.yml
- target:
    kind: ConfigMap
    name: argocd-rbac-cm
  path: argocd-rbac-cm.yml