apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- ingress.yaml

patches:
- target:
    kind: ConfigMap
    name: argocd-cm
  patch: |-
    - op: replace
      path: /data/url
      value: https://argocd.tineochristopher.com
- target:
    kind: ConfigMap
    name: argocd-cm
  patch: |-
    - op: replace 
      path: /data/oidc.config 
      value: |
        name: Keycloak
        issuer: https://keycloak.tineochristopher.com/realms/kubernetes
        clientID: argocd
        clientSecret: $oidc.keycloak.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
      