argo-cd:
  global:
    domain: &argoDomain argocd.tineochristopher.com

  server:
    ingress:
      enabled: true
      tls: true
      hostname: *argoDomain
      extraTls:
      - hosts:
        - *argoDomain
        secretName: argocd-server-tls

    certificate:
      enabled: true
      issuer:
        kind: ClusterIssuer
        name: *clusterIssuer
