argo-cd:
  global:
    domain: argocd.tineochristopher.com
  configs:
    params:
      server.insecure: true

  dex:
    enabled: false

  configs:
    cm:
      application.instanceLabelKey: argocd.argoproj.io/instance

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls: true