argo-cd:
  global:
    domain: argocd.tineochristopher.com

  certificate:
    enabled: true

  configs:
    params:
      server.insecure: true

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        external-dns.alpha.kubernetes.io/target: a273a7f4-6ef1-44a6-82f7-48c6ee866673.cfargotunnel.com
      tls: true

  dex:
    enabled: false

  configs:
    cm:
      application.instanceLabelKey: argocd.argoproj.io/instance