apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: directory
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: iam-demo
  source:
    repoURL: https://github.com/TineoC/homelab.git
    targetRevision: HEAD
    path: control-plane/manifests/directory
  destination:
    server: https://kubernetes.default.svc
    namespace: directory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
