apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - RequestReceived
rules:
  - level: RequestResponse
    verbs: ["create", "update", "patch", "delete", "deletecollection"]
    resources:
      - group: ""
        resources:
          - "*"
      - group: "apps"
        resources: ["deployments", "statefulsets"]
      - group: "networking.k8s.io"
        resources: ["networkpolicies"]

  - level: Metadata
    verbs: ["get", "list", "watch", "delete"]
    resources:
      - group: ""
        resources: ["secrets", "configmaps"]

  - level: Request
    users:
      - "system:serviceaccount:flux-system:kustomize-controller"
      - "system:serviceaccount:flux-system:helm-controller"
    verbs: ["create", "update", "patch", "delete"]
    resources:
      - group: "kustomize.toolkit.fluxcd.io"
        resources: ["kustomizations"]
      - group: "helm.toolkit.fluxcd.io"
        resources: ["helmreleases"]
      - group: "source.toolkit.fluxcd.io"
        resources: ["*"]
