apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./web
- ./oauth2-proxy

namespace: protected

configMapGenerator:
- name: app-config
  literals:
  - host=web.tineochristopher.com
  - tls-secret=protected-web-tls

replacements:
- source:
    kind: ConfigMap
    name: app-config
    fieldPath: data.host
  targets:
  - select:
      kind: Ingress
      name: web
    fieldPaths:
    - metadata.annotations.[external-dns.alpha.kubernetes.io/hostname]
    - spec.tls.0.hosts.0
    - spec.rules.0.host
  - select:
      kind: Ingress
      name: oauth2-proxy
    fieldPaths:
    - spec.rules.0.host
    - spec.tls.0.hosts.0
  - select:
      kind: Ingress
      name: external-auth-oauth2
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: app-config
    fieldPath: data.tls-secret
  targets:
  - select:
      kind: Ingress
      name: web
    fieldPaths:
    - spec.tls.0.secretName
  - select:
      kind: Ingress
      name: oauth2-proxy
    fieldPaths:
    - spec.tls.0.secretName