apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cloudflare-cluster-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-secrets
    creationPolicy: Owner
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: cloudflare-api-key
        property: apiKey
