apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-plane
spec:
  project: default
  source:
    repoURL: https://github.com/TineoC/homelab.git
    targetRevision: HEAD
    path: control-plane/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
