apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-plane
spec:
  project: default
  source:
    repoURL: https://github.com/TineoC/homelab.git
    targetRevision: main
    path: control-plane/apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
