apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
      values: |
        ingressShim:
          defaultIssuerName: "letsencrypt-prod"
          defaultIssuerKind: "ClusterIssuer"
    repoURL: https://charts.jetstack.io
    targetRevision: v1.17.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
