apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-operator
spec:
  project: default
  destination:
    namespace: cloudflare-operator
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/TineoC/homelab.git
    targetRevision: HEAD
    path: control-plane/manifests/cloudflare-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
