apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    path: control-plane/manifests/ingress-nginx
    helm:
      values: |
        controller:
          ingressClassResource:
            default: true
          service:
            type: ClusterIP
          allowSnippetAnnotations: true
          config:
            annotations-risk-level: "Critical"
    targetRevision: 4.13.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
