apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 24.8.1
    helm:
      values: |
        auth:
          adminUser: admin
          adminPassword: admin
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: keycloak.tineochristopher.com
          ingressClassName: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
