apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 24.8.1
    helm:
      values: |
        auth:
          adminUser: admin
          adminPassword: admin
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: keycloak.tineochristopher.com
          ingressClassName: nginx
          annotations:
            external-dns.alpha.kubernetes.io/hostname: keycloak.tineochristopher.com
            cert-manager.io/cluster-issuer: letsencrypt-staging
            nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
            external-dns.alpha.kubernetes.io/target: 96.248.109.98
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
