apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metal-lb
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  source:
    repoURL: https://github.com/tineoc/homelab
    path: control-plane/manifests/metal-lb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
