apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: control-plane
  namespace: argocd
spec:
  sourceRepos: ["https://github.com/TineoC/homelab.git"]
  sourceNamespaces: ["*"]
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  namespaceResourceBlacklist:
    - group: "*"
      kind: "*"
