apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: keycloak-backend
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  endpoints:
  - fqdn:
      hostname: keycloak.internal.tineochristopher.com
      port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: keycloak-backend-tls
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetRefs:
  - group: gateway.envoyproxy.io
    kind: Backend
    name: keycloak-backend
  validation:
    caCertificateRefs:
    - group: ""
      kind: ConfigMap
      name: keycloak-ca
    hostname: keycloak.internal.tineochristopher.com
