apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: private-gw
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "*.internal.tineochristopher.com"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: private-gw-tls