apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: login-anchor
  namespace: envoy-gateway-system
spec:
  parentRefs:
  - name: private-gw
    sectionName: apps
  hostnames: [ "login.apps.internal.tineochristopher.com" ]
  rules:
  - matches:
    - path: { type: Exact, value: /robots.txt }
    backendRefs:
    - name: placeholder-svc
      port: 80
  - matches:
    - path:
        type: Exact
        value: /favicon.ico
    backendRefs:
    - name: placeholder-svc
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: placeholder-svc
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: placeholder-svc
  namespace: envoy-gateway-system
spec:
  selector:
    app: placeholder
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder
  namespace: envoy-gateway-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
      - name: placeholder
        image: nginx:alpine
        ports:
        - containerPort: 80
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          cat > /etc/nginx/conf.d/default.conf <<'NGINX'
          server {
            listen 80;
            server_name _;
        
            # 204 for favicon.ico so no redirect path ever happens
            location = /favicon.ico { return 204; }
        
            location = /robots.txt  { root /usr/share/nginx/html; try_files /robots.txt =404; }
        
            location / {
              root /usr/share/nginx/html;
              try_files $uri /index.html;
            }
          }
          NGINX
        
          # minimal files
          printf 'User-agent: *\nDisallow:\n' > /usr/share/nginx/html/robots.txt
        
          # Inline data-URL favicon so the browser doesn't ask for /favicon.ico at all
          cat > /usr/share/nginx/html/index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <title>Login anchor placeholder</title>
          <link rel="icon" href="data:,">
          <h1>Login anchor placeholder - OIDC callback OK</h1>
          HTML
        
          exec nginx -g 'daemon off;'
        