apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: login-anchor
  namespace: envoy-gateway-system
spec:
  parentRefs:
  - name: private-gw
    sectionName: apps
  hostnames: [ "login.apps.internal.tineochristopher.com" ]
  rules:
  - matches:
    - path: { type: PathExact, value: /favicon.ico }
    backendRefs:
    - name: placeholder-svc
      port: 80
  - matches:
    - path: { type: PathPrefix, value: / }
    backendRefs:
    - name: placeholder-svc
      port: 80
