{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls: {{ toYaml .Values.ingress.tls | nindent 4 }}
  rules:
  - host: {{ .Values.websiteName }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: {{ .Values.service.externalPort }}
{{ end }}