apiVersion: v2
name: keycloak
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: keycloak
    version: 24.8.1
    repository: https://charts.bitnami.com/bitnami
    condition: keycloak.enabled
    tags:
      - keycloak
