keycloak:
  auth:
    existingSecret: keycloak-admin-creds
    passwordKey: admin-password
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostname: keycloak.tineochristopher.com
    ingressClassName: nginx
    extraTLS:
    - hosts:
        - keycloak.tineochristopher.com
      secretName: keycloak-tls
    annotations:
      external-dns.alpha.kubernetes.io/hostname: keycloak.tineochristopher.com
      cert-manager.io/cluster-issuer: letsencrypt-staging
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      external-dns.alpha.kubernetes.io/target: 96.248.109.98