keycloak:
  auth:
    adminUser: admin
    existingSecret: keycloak-admin-creds
    passwordSecretKey: admin-password
  postgresql:
    enabled: true
    auth:
      username: keycloak
      database: keycloak
      existingSecret: keycloak-db-credentials
      secretKeys:
        userPasswordKey: password
  ingress:
    enabled: true
    tls: true
    ingressClassName: nginx
    hostname: keycloak.tineochristopher.com
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: keycloak.tineochristopher.com
      external-dns.alpha.kubernetes.io/target: 96.248.109.98