keycloak:
  auth:
    adminUser: admin
    existingSecret: keycloak-admin-creds
    passwordSecretKey: admin-password
  postgresql:
    enabled: true
    auth:
      username: keycloak
      database: keycloak
      existingSecret: keycloak-db-credentials
      secretKeys:
        userPasswordKey: password
  production: true
  proxy: edge
  extraEnvVars:
  - name: KC_PROXY
    value: edge
  - name: KC_HOSTNAME
    value: keycloak.internal.tineochristopher.com
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_HOSTNAME_STRICT
    value: "false"
  ingress:
    enabled: false
