keycloak:
  auth:
    existingSecret: keycloak-admin-creds
    passwordSecretKey: admin-password
  service:
    type: ClusterIP
  ingress:
    tls: true
    enabled: true
    hostname: keycloak.tineochristopher.com
    ingressClassName: nginx
    extraTls:
    - hosts:
        - keycloak.tineochristopher.com
      secretName: keycloak-tls
    annotations:
      external-dns.alpha.kubernetes.io/hostname: keycloak.tineochristopher.com
      cert-manager.io/cluster-issuer: letsencrypt-staging
      external-dns.alpha.kubernetes.io/target: 96.248.109.98