keycloak:
  auth:
    adminUser: admin
    existingSecret: keycloak-admin-creds
    passwordSecretKey: admin-password
  service:
    type: ClusterIP
  postgresql:
    enabled: true
    auth:
      username: keycloak
      database: keycloak
      existingSecret: keycloak-db-credentials
      secretKeys:
        userPasswordKey: password
    architecture: standalone
  ingress:
    enabled: true
    ingressClassName: nginx
    tls: true
    hostname: keycloak.tineochristopher.com
    extraTLS:
    - hosts:
        - keycloak.tineochristopher.com
      secretName: keycloak-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
      external-dns.alpha.kubernetes.io/hostname: keycloak.tineochristopher.com
      external-dns.alpha.kubernetes.io/target: 96.248.109.98