- name: Fetch RKE2 join token from control plane
  shell: cat /var/lib/rancher/rke2/server/node-token
  register: rke2_join_token
  changed_when: false
  delegate_to: "{{ groups['primary_servers'][0] }}"

- name: Set RKE2 token fact
  set_fact:
    rke2_token: "{{ rke2_join_token.stdout }}"

- name: Configure RKE2 agent config file from template
  template:
    src: config-agent.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0644"
  vars:
    server: "https://{{ hostvars[groups['primary_servers'][0]].ansible_host }}:9345"
    token: "{{ rke2_token }}"
    node_name: "{{ inventory_hostname }}"
    write_kubeconfig_mode: "0644"

- name: Download and install RKE2 agent
  shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION={{ rke2_version }} INSTALL_RKE2_TYPE="agent" sh -
  args:
    creates: /usr/local/bin/rke2

- name: Enable and start RKE2 agent
  systemd:
    name: rke2-agent
    enabled: yes
    state: restarted
