---
- name: Ensure required dependencies are installed
  apt:
    name:
      - curl
      - unzip
    state: present

- name: Ensure RKE2 directory exists
  file:
    path: /etc/rancher/rke2
    state: directory
    mode: "0755"
