apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: envoy-gateway-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store
  target:
    name: cloudflare-api-key
    creationPolicy: Owner
  data:
  - secretKey: apiKey
    remoteRef:
      key: cloudflare
      property: token
