apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 30m
  releaseName: external-dns
  targetNamespace: external-dns
  storageNamespace: external-dns
  dependsOn:
    - name: external-secrets
  chart:
    spec:
      chart: ./control-plane/manifests/external-dns
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
    remediation: { retries: 3 }
  upgrade:
    remediation: { retries: 3 }
